import type { CapacitorConfig } from '@capacitor/cli';

const isDev = process.env.NODE_ENV === 'development';

const config: CapacitorConfig = {
  appId: 'com.eightyroad.app',
  appName: '80road',

  // The static export output directory — generated by `next build` with MOBILE_BUILD=true.
  // Run `npx cap sync` after every new build to copy updated assets to the native projects.
  webDir: 'out',

  // ── Development Server (Live Reload) ───────────────────────────────────────
  // In development, point Capacitor at the Next.js dev server instead of
  // the static `out/` folder. This enables hot reload on device during development.
  // Remove or comment this block before running a production build + cap sync.
  ...(isDev && {
    server: {
      // Replace with your machine's LAN IP if testing on a physical device.
      // Use `ipconfig` (Windows) or `ifconfig` (Mac/Linux) to find it.
      // url: 'http://192.168.1.x:3000',
      cleartext: true, // Allow HTTP for local dev server
    },
  }),

  // ── Plugin Configuration ───────────────────────────────────────────────────
  plugins: {
    PushNotifications: {
      // Controls how notifications are presented when the app is in the foreground (iOS).
      // 'alert'  — show a notification banner
      // 'badge'  — update the app badge count
      // 'sound'  — play the notification sound
      presentationOptions: ['badge', 'sound', 'alert'],
    },

    SplashScreen: {
      // Show the splash screen for at most 2 seconds, then auto-hide.
      // Call SplashScreen.hide() manually after the app finishes loading
      // for the smoothest experience.
      launchShowDuration: 2000,
      launchAutoHide: true,
      backgroundColor: '#1a2744', // 80road navy — matches --brand-navy
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      iosSpinnerStyle: 'small',
    },

    // Keyboard resizing behaviour.
    // 'body' — the page body resizes when the keyboard opens (recommended for forms).
    // Without this, fixed-position elements (bottom nav) can overlap the keyboard.
    Keyboard: {
      resize: 'body',
      resizeOnFullScreen: true,
    },
  },

  // ── Android-specific ───────────────────────────────────────────────────────
  android: {
    // Background colour shown before the WebView paints — eliminates white flash
    // on OLED screens and matches the app's dark mode background.
    backgroundColor: '#FFFFFF', // Light mode default (matches CSS --background)

    // Hides native logging in production builds submitted to Play Store.
    // Set to 'debug' locally for verbose Capacitor logs.
    loggingBehavior: isDev ? 'debug' : 'none',
  },

  // ── iOS-specific ───────────────────────────────────────────────────────────
  ios: {
    // Prevents white flash before WebView renders content.
    backgroundColor: '#FFFFFF', // Light mode default

    // Hides native logging from Xcode console in production.
    loggingBehavior: isDev ? 'debug' : 'none',

    // Matches the scheme used in App.xcworkspace.
    // Change if your Xcode scheme has a different name.
    scheme: 'App',
  },
};

export default config;
